### ISSUE TITLE
naming

### ISSUE THREAD

**Issue by onno-timmerman** [withlogicco/django-prose#115]
A bti confusing is that there is a django-prose-editor it uses a diffrent editor but it to similar name
Maybe this is a bit confusing namen:
https://github.com/matthiask/django-prose-editor

One of the two maybe best to rename? django-trix-editor ??

**Comment by parisk** [comment]
Yup, could be confusing indeed, but I do not believe it's going to be an issue for any of the libraries.

Also, it was intentionally named like this to avoid any tying with editor implementation. In the future we might move to another editor, or even make this configurable.

We can not do anything here.
