### ISSUE TITLE
Error: 'Select a valid choice. That choice is not one of the available choices.'

### ISSUE THREAD

**Issue by hengage** [withlogicco/django-prose#20]
I have this error when I try to make a post: "Select a valid choice. That choice is not one of the available choices."

![image](https://user-images.githubusercontent.com/76456538/203874205-edfed928-5594-45b5-ae43-f68cab72091c.png)

Is this some sort of error from my end? Or from django-prose?

here is my model

![image](https://user-images.githubusercontent.com/76456538/203874369-d936a5e0-384a-44ce-b483-eabc9005615d.png)

**Comment by parisk** [comment]
Hi @hengage,

The model looks OK. Based on the error you receive I speculate there is an issue with how you are rendering a form in your website. Is this correct?

In the admin site it should display a dropdown list for the to pick an `ArticleContent`, since it's a relation field. Can you confirm this as well?

**Comment by hengage** [comment]
Hey @parisk, from your explanation it seems like I have to select an already existing article. Am i right?

What I am trying to achieve with it is to make it like a text field so I can write my content and post. Just like RichTextField() does.

I guess I just have to use RichtextField and increase its height with CSS. Which I already did btw.

**Comment by parisk** [comment]
If you intend to store long-form content (e.g. an article's body) in the database, I suggest you use a separate model and reference it with a ForeignKey. It will result in significantly lighter queries, when you `SELECT` multiple records.

In that case you would need to create the `body` model first and then create the `post` model, so you can reference the `body` model.

Inline formsets[^1] might also be of help here.

[^1]: https://docs.djangoproject.com/en/4.1/topics/forms/modelforms/#inline-formsets

**Comment by hengage** [comment]
Alright @parisk I'll create an issue for it on my project and look into it going forward. Thank you.

If you would like to see the finished work when it's in production I can send you the link.

Thanks for the help.

**Comment by parisk** [comment]
We could actually add a **Real world use cases** in the README to indicate products using Django Prose. That would be great.

**Comment by hengage** [comment]
Great. Absloutely look forward to it when I put the project out live. 

It's a blog app I am making to put out contents by me and few friends who are writers.
