### ISSUE TITLE
RichTextfield does not render without using {{ form.media }} on templates

### ISSUE THREAD

**Issue by hengage** [withlogicco/django-prose#22]
I discovered something while using prose for my app,  the content field does not render unless I include {{ form.media }}

![image](https://user-images.githubusercontent.com/76456538/204072861-10c416a4-8d0b-4a4a-87ff-e220e77715dd.png)

You can see the {{ form.media }} in my code screenshot.

Without this, the Richtextfield does not render on my webpage

Here is a screenshot without it:

![image](https://user-images.githubusercontent.com/76456538/204072935-b6f4e058-f6d4-4649-9551-fbae8a0c3085.png)

you can see the 'content' field is empty

Now, it renders when I include  {{ form.media }}
A screenshot below:
![image](https://user-images.githubusercontent.com/76456538/204072964-3827c275-41db-4665-af76-579819c4a905.png)

Why does this happen? It's surprising because it is not indicated on the Readme for Prose.

Btw it does render on the admin area with no issue

**Comment by parisk** [comment]
That's correct. It needs `form.media`, so that it loads Trix and its CSS. Tracking this in https://github.com/withlogicco/django-prose/labels/documentation, so we can fix it in the README.

Contributions are always welcome!

**Comment by hengage** [comment]
Okay good to know. Happy to help.

**Comment by parisk** [comment]
@

**Comment by parisk** [comment]
Reopening this, since we want to fix it.



> Okay good to know. Happy to help.

We would be super happy to review a Pull Request from you, if you wish. What we need to do here is add a new **Rendering in forms**, at the bottom of the **Usage** section:

```md
## Usage

...

### Rendering in forms

...documentation here
```

**Comment by parisk** [comment]
Closed in https://github.com/withlogicco/django-prose/pull/23
