### ISSUE TITLE
Loading Prose on Django 5.0

### ISSUE THREAD

**Issue by alexandremjacques** [withlogicco/django-prose#75]
Hi,

I'm having a issue where `{{ form.media }}` isn't loading the js and CSS necessary to start Trix. I've tried looking at the source code and I couldn't find anything that would point to an error.

It just won't load and I can see no errors in Django logs nor in the browser console.

This also happens on admin pages. I can only see a regular `textarea` where the Trix editor should be.

Any help would be appreciated.

TIA 

PS: the instalation went OK since I the migrations also ran without errors. URLs are loaded and Django starts fine.

----
I've just tried to inspect my form on Django shell and I can see that nothing is being loaded:

<img width="752" alt="image" src="https://github.com/withlogicco/django-prose/assets/1953298/065c61e6-0621-4250-ac06-066ba28c24da">

My form code:

```python
from prose.fields import RichTextField

class NewPriceQuoteForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        agency_id = kwargs.pop('agency_id', None)
        super().__init__(*args, **kwargs)

    message = RichTextField()
```

**Comment by alexandremjacques** [comment]
Never mind. I found the issue. My model field was not set as `RichTextField`.

**Comment by parisk** [comment]
Happy you resolved your issue @alexandremjacques!
